# Generated by Django 5.0.6 on 2026-04-27 05:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('tier', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
                ('incantation', models.TextField(blank=True)),
                ('unlock_threshold', models.PositiveIntegerField(help_text='Lucid dream count required to unlock this spell.')),
                ('category', models.CharField(choices=[('stabilization', 'Stabilization'), ('manifestation', 'Manifestation'), ('transformation', 'Transformation'), ('environmental', 'Environmental')], max_length=20)),
            ],
            options={
                'ordering': ('tier', 'unlock_threshold', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SpellCast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('dream_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spell_casts', to='journal.dreamentry')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casts', to='spells.spell')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_casts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-cast_at',),
                'indexes': [models.Index(fields=['user', '-cast_at'], name='spells_spel_user_id_e4386f_idx')],
            },
        ),
    ]
