import uuid
from datetime import datetime, timedelta, timezone as dt_timezone

from django.conf import settings
from django.db import models
from django.utils import timezone


class Reminder(models.Model):
    """User-configured reminder.

    Two cadence patterns cover the v1 use cases:
      - 'daily'    fires once per day at `time_of_day`
      - 'interval' fires every `interval_minutes` between `time_of_day` and `active_until`

    `next_fire_at` is recomputed after every fire by the scheduler endpoint.
    All times are stored in UTC; the user's timezone is on the User model.
    """

    class Kind(models.TextChoices):
        RC = "rc", "Reality check"
        MEDITATION = "meditation", "Meditation"
        JOURNAL = "journal", "Journal"
        WBTB = "wbtb", "Wake back to bed"
        CUSTOM = "custom", "Custom"

    class Cadence(models.TextChoices):
        DAILY = "daily", "Once per day"
        INTERVAL = "interval", "Every N minutes during a window"

    class Channel(models.TextChoices):
        PUSH = "push", "Web push"
        EMAIL = "email", "Email"
        BOTH = "both", "Push + email"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="reminders"
    )
    kind = models.CharField(max_length=16, choices=Kind.choices)
    label = models.CharField(max_length=80, blank=True)
    cadence = models.CharField(max_length=16, choices=Cadence.choices)
    time_of_day = models.TimeField(help_text="In user's local timezone (HH:MM).")
    active_until = models.TimeField(
        null=True, blank=True, help_text="End of fire window for interval cadence."
    )
    interval_minutes = models.PositiveIntegerField(
        null=True, blank=True, help_text="Minutes between fires for interval cadence."
    )
    channel = models.CharField(max_length=8, choices=Channel.choices, default=Channel.PUSH)
    enabled = models.BooleanField(default=True)
    next_fire_at = models.DateTimeField(db_index=True)
    last_fired_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    practice_slug = models.CharField(
        max_length=64,
        blank=True,
        db_index=True,
        help_text="If set, this reminder is bound to a specific weekly-program practice.",
    )

    class Meta:
        ordering = ("next_fire_at",)
        indexes = [models.Index(fields=("enabled", "next_fire_at"))]

    def __str__(self) -> str:
        return f"{self.user_id} {self.kind} {self.cadence} @ {self.time_of_day}"

    def compute_next_fire(self, now: datetime | None = None) -> datetime:
        """Compute the next UTC datetime this reminder should fire.

        Uses the user's local timezone to interpret time_of_day. Falls back to UTC
        if zoneinfo can't resolve the user's TZ string.
        """
        try:
            import zoneinfo

            tz = zoneinfo.ZoneInfo(self.user.timezone or "UTC")
        except Exception:
            tz = dt_timezone.utc

        now = now or timezone.now()
        local_now = now.astimezone(tz)

        if self.cadence == self.Cadence.DAILY:
            candidate = local_now.replace(
                hour=self.time_of_day.hour,
                minute=self.time_of_day.minute,
                second=0,
                microsecond=0,
            )
            if candidate <= local_now:
                candidate += timedelta(days=1)
            return candidate.astimezone(dt_timezone.utc)

        # interval cadence
        start = local_now.replace(
            hour=self.time_of_day.hour,
            minute=self.time_of_day.minute,
            second=0,
            microsecond=0,
        )
        end = local_now.replace(
            hour=(self.active_until or self.time_of_day).hour,
            minute=(self.active_until or self.time_of_day).minute,
            second=0,
            microsecond=0,
        )
        if end <= start:
            end += timedelta(days=1)
        step = timedelta(minutes=self.interval_minutes or 60)

        cursor = start
        while cursor <= local_now:
            cursor += step
        if cursor > end:
            cursor = start + timedelta(days=1)
        return cursor.astimezone(dt_timezone.utc)


class PushSubscription(models.Model):
    """Browser-side Web Push subscription registered by a logged-in user.

    A user can have many — one per device/browser. The `endpoint` is unique;
    push services (Apple, Google, Mozilla) issue stable URLs we POST to.
    `p256dh` and `auth` are URL-safe base64 keys generated by `pushManager.subscribe`.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="push_subscriptions"
    )
    endpoint = models.URLField(max_length=2048, unique=True)
    p256dh = models.CharField(max_length=255)
    auth = models.CharField(max_length=255)
    user_agent = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_seen_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)
        indexes = [models.Index(fields=("user",))]

    def __str__(self) -> str:
        host = self.endpoint.split("/")[2] if "://" in self.endpoint else self.endpoint
        return f"{self.user_id} {host}"


class NotificationLog(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    reminder = models.ForeignKey(
        Reminder, on_delete=models.CASCADE, related_name="notifications"
    )
    channel = models.CharField(max_length=8, choices=Reminder.Channel.choices)
    delivered = models.BooleanField(default=False)
    error = models.TextField(blank=True)
    sent_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-sent_at",)

    def __str__(self) -> str:
        return f"{self.reminder_id} {self.channel} {'ok' if self.delivered else 'fail'}"
