# Generated by Django 5.0.6 on 2026-04-27 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('rc', 'Reality check'), ('meditation', 'Meditation'), ('journal', 'Journal'), ('wbtb', 'Wake back to bed'), ('custom', 'Custom')], max_length=16)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('cadence', models.CharField(choices=[('daily', 'Once per day'), ('interval', 'Every N minutes during a window')], max_length=16)),
                ('time_of_day', models.TimeField(help_text="In user's local timezone (HH:MM).")),
                ('active_until', models.TimeField(blank=True, help_text='End of fire window for interval cadence.', null=True)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, help_text='Minutes between fires for interval cadence.', null=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('both', 'Email + push')], default='email', max_length=8)),
                ('enabled', models.BooleanField(default=True)),
                ('next_fire_at', models.DateTimeField(db_index=True)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('next_fire_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('both', 'Email + push')], max_length=8)),
                ('delivered', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reminders.reminder')),
            ],
            options={
                'ordering': ('-sent_at',),
            },
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['enabled', 'next_fire_at'], name='reminders_r_enabled_377aec_idx'),
        ),
    ]
