# Generated by Django 5.0.6 on 2026-05-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_pushsubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='reminders_p_user_id_edca04_idx',
            old_name='reminders_p_user_id_b28a0a_idx',
        ),
        migrations.AddField(
            model_name='reminder',
            name='practice_slug',
            field=models.CharField(blank=True, db_index=True, help_text='If set, this reminder is bound to a specific weekly-program practice.', max_length=64),
        ),
    ]
