# Generated by Django 5.0.6 on 2026-05-04 05:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('newcomer', "Never recalled a dream / haven't tried lucid"), ('recaller', 'Remembers dreams most mornings, no lucid yet'), ('dabbler', '1–3 lucid dreams ever'), ('practitioner', 'Lucid monthly+, knows MILD/WBTB'), ('adept', 'Lucid weekly+, wants depth/control')], max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='goals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='typical_bedtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
