# Generated by Django 5.0.6 on 2026-04-27 05:42

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgram',
            fields=[
                ('week_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('title', models.CharField(max_length=80)),
                ('focus', models.CharField(max_length=160)),
                ('daily_practices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None)),
                ('primary_technique', models.CharField(choices=[('DILD', 'DILD'), ('WILD', 'WILD'), ('MILD', 'MILD'), ('WBTB', 'WBTB'), ('SSILD', 'SSILD')], max_length=16)),
                ('technique_detail', models.TextField()),
                ('recommended_chakras', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), default=list, size=None)),
            ],
            options={
                'ordering': ('week_number',),
            },
        ),
    ]
