# Generated by Django 5.0.6 on 2026-04-27 05:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('hand', 'Look at hands'), ('nose', 'Pinch nose breath'), ('text', 'Re-read text'), ('clock', 'Read clock twice'), ('light', 'Light switch'), ('mirror', 'Look in mirror'), ('memory', 'Recall last hour'), ('jump', 'Jump and float')], max_length=16)),
                ('was_lucid_trigger', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reality_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-performed_at',),
                'indexes': [models.Index(fields=['user', '-performed_at'], name='reality_che_user_id_0c5ac7_idx')],
            },
        ),
    ]
