# Generated by Django 5.0.6 on 2026-04-27 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChakraSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chakra_id', models.CharField(choices=[('root', 'Root'), ('sacral', 'Sacral'), ('solar', 'Solar'), ('heart', 'Heart'), ('throat', 'Throat'), ('thirdeye', 'Thirdeye'), ('crown', 'Crown')], max_length=16)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('frequency_hz', models.PositiveIntegerField(blank=True, null=True)),
                ('mantra', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chakra_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-completed_at',),
                'indexes': [models.Index(fields=['user', '-completed_at'], name='meditation__user_id_d8d3d1_idx'), models.Index(fields=['user', 'chakra_id'], name='meditation__user_id_d4058a_idx')],
            },
        ),
    ]
