# Generated by Django 5.0.6 on 2026-04-27 05:42

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('dream_date', models.DateField()),
                ('is_lucid', models.BooleanField(default=False)),
                ('lucidity_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('technique_used', models.CharField(blank=True, choices=[('DILD', 'Dream-Initiated Lucid Dream'), ('WILD', 'Wake-Initiated Lucid Dream'), ('MILD', 'Mnemonic-Induced Lucid Dream'), ('WBTB', 'Wake Back to Bed'), ('SSILD', 'Senses-Initiated Lucid Dream'), ('other', 'Other')], default='', max_length=16)),
                ('vividness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('emotions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('transition_stages_reached', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-dream_date', '-created_at'),
                'indexes': [models.Index(fields=['user', '-dream_date'], name='journal_dre_user_id_68c1f1_idx'), models.Index(fields=['user', 'is_lucid'], name='journal_dre_user_id_24b5ca_idx')],
            },
        ),
    ]
